name: CI

on:
  push:
  pull_request:
  release:
  workflow_dispatch:

jobs:
  build:
    steps:
      - uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '10.x'
          
      - uses: bahmutov/npm-install@v1

      - name: Install JS dependencies
        run:  yarn install

      - name: Test Coverage
        run: yarn test:coverage

      - name: Code Lint 
        run: yarn lint 
